version = 1

[project]
name = "DevTool"

[dev.environment]
profile = "base"
image = "ghcr.io/thinkerqaq/dev-base@sha256:f922f24b2dd917faa87bfc090dd90321aaf82651cc9a2de320a22519c3b77a8e"

[extension.project]
type = "go"
module = "./devcontrol"
package = "./cmd/provider"

[extension.environment]
type = "go"
module = "."
package = "./extensions/environment/docker/cmd/provider"

[extension.runtime]
type = "go"
module = "."
package = "./extensions/runtime/dagger/cmd/provider"

[extension.codegraph]
type = "go"
module = "."
package = "./extensions/intelligence/codegraph/cmd/provider"

[extension.lsp]
type = "go"
module = "."
package = "./extensions/intelligence/serena/cmd/provider"

[extension.sourcegraph]
type = "go"
module = "."
package = "./extensions/intelligence/sourcegraph/cmd/provider"

[extension.scm]
type = "go"
module = "."
package = "./extensions/scm/github/cmd/provider"

[service.environment]
provider = "environment.docker"

[service.portable-runtime]
provider = "runtime.dagger"

[service.code-indexed]
provider = "intelligence.codegraph"

[service.code-realtime]
provider = "intelligence.lsp.serena"

[service.scm-publish]
provider = "scm.github"

[code]
workspaces = ["."]


[profile.railway.extension.environment]
type = "go"
module = "."
package = "./extensions/environment/local/cmd/provider"

[profile.railway.service.environment]
provider = "environment.local"


[profile.sourcegraph.service.code-indexed]
provider = "intelligence.sourcegraph"
