version = 1

[project]
name = "DevTool"

[extension.project]
source = "./devcontrol/cmd/provider"

[extension.runtime]
source = "builtin:runtime.dagger"

[service.portable-runtime]
provider = "runtime.dagger"
